- hosts: all
  become: true
  gather_facts: false
  pre_tasks:
  - name: Install ansible prerequisites
    raw: bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qqy python-minimal)"
    register: output
    changed_when: output.stdout != ""
  - name: Gathering Facts
    setup:
  roles:
    - apache2
    - mysql
    - php-fpm
  vars:
    mysql_root_password: "R34lS3cuR3P4$$w0rd"
