- name: Security assertions
  hosts: [ 'all' ]
  tags: [ 'play::security-assertions' ]
  gather_facts: False
  become: False

  tasks:

    - name: Check for Ansible version without known vulnerabilities
      assert:
        that:
          - 'ansible_version.full | version_compare("2.1.5.0", ">=")'
          - '((ansible_version.minor == 2) and (ansible_version.full | version_compare("2.2.2.0", ">="))) or (ansible_version.minor != 2)'
        msg: 'VULNERABLE or unsupported Ansible version DETECTED, please update to Ansible >= v2.1.5 or a newer Ansible release >= v2.2.2! To skip, add "--skip-tags play::security-assertions" parameter. Check the debops-playbook changelog for details. Exiting.'
      run_once: True
      delegate_to: 'localhost'